# Generated by Django 4.1 on 2022-10-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=20)),
                ('asunto', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
