# Generated by Django 4.1 on 2022-10-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg_user',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='msg_user',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='msg_user',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
